### ISSUE TITLE
no position information

### ISSUE THREAD

**Issue by ZoomDomain** [Nidre/Unity-Audio-Sequencer#4]
Hi there, I was after a program that lets me adjust playback time of files and playback speed, thanks for your program, i tried to figure it out, i couldnt find references to the files being played or position info, and a sequencer has two main functions... file ID 1-8 for an 8 track and playback position and volume...

I was probably going to write my own one, but i just wanted to see if i could find a sequencer exampe playing 8 tracks concurrently with some control handles that i could understand. 

Thanks... the lack of position settings in the tutorial is confusing.

**Comment by Ludomancer** [comment]
@ZoomDomain 

Does GetPercentage() method in Sequencer.cs help?

If not, can you please explain what exactly do you need? Maybe I can spare some time to implement this, or you can spare some and send me a pull-request! :) I would appreciate that!

**Comment by Ludomancer** [comment]
@ZoomDomain

Added CurrentStep and NumberOfSteps in Version 0.3. Events also send those values as parameters. I think this should be doing what you need. You can get current position by Events or new properties in Sequencer.cs

**Comment by ZoomDomain** [comment]
Hi, Thanks alot that's brilliant, i understand. i'm working on it it's very helpful. nice coding! thanks
