### ISSUE TITLE
BPM doesn't live change on Android

### ISSUE THREAD

**Issue by Souk21** [Nidre/Unity-Audio-Sequencer#5]
Everything works just great in the Editor, but as soon as build, the bpm doesn't change when I click BPM+/BPM- 

I solved the issue by removing `#if UNITY_EDITOR` around the `oldBpm` and `FixedUpdate` calls

**Comment by Ludomancer** [comment]
@Souk21 

Calling SetBpm method should change the bpm. The part you've removed basically does the same thing, but slower since it checks every single LateUpdate. The part was intended for Editor use only,
